/** Public adapter protocol facade. The browser-neutral wire contract lives once. */
export {
  clientNotificationValidators,
  customRequestParamsValidators,
  customRequestResultValidators,
  isCustomRequestMethod,
  isEditorNavigationEvent,
  isJsonRpcMessageEnvelope,
  isJsonRpcResponseEnvelope,
  isRenderFrame,
  isServerNotificationMethod,
  isWebviewInboundMessage,
  serverNotificationValidators,
  shouldForwardEditorNavigation,
} from "../../../web/preview-client/protocol.mjs";
export { PROTOCOL_VERSION as protocolVersion } from "../../../web/preview-client/protocol.mjs";
export type {
  AttachDocumentResult,
  CheckpointDocumentResult,
  ClientNotificationMap,
  CommandResult,
  CreatePreviewResult,
  CustomRequestMap,
  Diagnostic,
  EditorNavigationEvent,
  ExecuteCommandParams,
  GetNoteOptionsParams,
  GetNoteOptionsResult,
  InitializeParams,
  InitializeResult,
  JsonValue,
  JsonRpcMessageEnvelope,
  JsonRpcResponseEnvelope,
  LspMethod,
  NoteCategoryOption,
  PreviewChangedParams,
  PreviewTarget,
  PublishDiagnosticsParams,
  RequestFullTextParams,
  RenderFrame,
  RpcId,
  ServerNotificationMap,
  ServerPreviewEventParams,
  SourcePosition,
  SourceNavigationEvent,
  SourceRange,
  Validator,
  WebviewInboundMessage,
} from "../../../web/preview-client/protocol.mjs";
