from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from _tools import ROOT, script_entrypoint


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def verify_architecture() -> None:
    required_contracts = (
        "ARCHITECTURE.md",
        "capabilities/clean-break-catalog.json",
        "capabilities/feature-inventory.json",
        "crates/fleximark-plugin-sdk/wit/fleximark-plugin-v1.wit",
        "crates/fleximark-protocol-codegen/Cargo.toml",
        "schemas/config.schema.json",
        "schemas/feature-inventory.schema.json",
        "schemas/plugin-manifest.schema.json",
        "schemas/protocol.schema.json",
        "web/preview-client/protocol.generated.mts",
    )
    for relative_path in required_contracts:
        path = ROOT / relative_path
        require(
            path.is_file() and path.stat().st_size > 0,
            f"{relative_path} is missing",
        )

    vscodeignore = set((ROOT / ".vscodeignore").read_text(encoding="utf-8").splitlines())
    require(
        "ARCHITECTURE.md" in vscodeignore,
        "ARCHITECTURE.md must not be included in the VSIX",
    )

    package_json = read_json(ROOT / "package.json")
    inventory = read_json(ROOT / "capabilities" / "feature-inventory.json")
    disposition_catalog = read_json(
        ROOT / "capabilities" / "clean-break-catalog.json"
    )
    adapter_source = "\n".join(
        (ROOT / "adapters" / "vscode" / "src" / file).read_text(
            encoding="utf-8"
        )
        for file in ("adapter.mts", "extension.mts")
    )
    require(package_json.get("main") == "./dist/extension.cjs", "unexpected extension entry point")
    require(
        package_json.get("activationEvents")
        == [
            "onLanguage:markdown",
            "workspaceContains:.fleximark/config.toml",
            "workspaceContains:.fleximark/fleximark.json",
        ],
        "unexpected activation events",
    )
    properties = package_json["contributes"]["configuration"]["properties"]
    for key in (
        "fleximark.browserPreviewPort",
        "fleximark.shouldSyncScroll",
        "fleximark.noteCategories",
        "fleximark.noteFileNamePrefix",
        "fleximark.noteFileNameSuffix",
        "fleximark.noteTemplates",
    ):
        require(key not in properties, f"{key} is service-owned")

    for dependency in package_json.get("dependencies", {}):
        require(
            re.search(r"^(remark|rehype|shiki|express$|ws$)", dependency) is None,
            f"{dependency} belongs outside the adapter",
        )

    require(inventory.get("schemaVersion") == 1, "unsupported inventory schema")
    capabilities = inventory["capabilities"]
    identifiers = [capability["id"] for capability in capabilities]
    require(len(set(identifiers)) == len(identifiers), "capability IDs must be unique")
    for capability in capabilities:
        require(bool(capability.get("owner")), f"{capability['id']} needs an owner")

    for clean_break_id, disposition in disposition_catalog["cleanBreaks"].items():
        require(
            all(
                disposition.get(field)
                for field in ("rationale", "replacement", "unsupportedBehavior")
            ),
            f"{clean_break_id} is incomplete",
        )
        require(
            disposition["releaseNoteId"] in disposition_catalog["releaseNotes"],
            f"{clean_break_id} references an unknown release note",
        )

    for removed_runtime in ("src", "media"):
        directory = ROOT / removed_runtime
        require(
            not directory.exists() or not any(path.is_file() for path in directory.rglob("*")),
            f"{removed_runtime}: legacy TypeScript runtime must not be shipped",
        )
    require(
        not (ROOT / "parserPlugin.js").exists(),
        "parserPlugin.js: legacy TypeScript runtime must not be shipped",
    )

    for schema in (
        "config.schema.json",
        "protocol.schema.json",
        "plugin-manifest.schema.json",
        "feature-inventory.schema.json",
    ):
        document = read_json(ROOT / "schemas" / schema)
        require(
            document.get("$schema") == "https://json-schema.org/draft/2020-12/schema",
            f"{schema} uses an unexpected JSON Schema draft",
        )

    protocol_schema = read_json(ROOT / "schemas" / "protocol.schema.json")
    generated_marker = "Generated by fleximark-protocol-codegen; DO NOT EDIT."
    require(
        protocol_schema.get("$comment") == generated_marker,
        "protocol.schema.json must be generated from the Rust protocol contract",
    )
    generated_typescript = (
        ROOT / "web" / "preview-client" / "protocol.generated.mts"
    ).read_text(encoding="utf-8")
    require(
        generated_typescript.startswith(f"// {generated_marker}\n"),
        "protocol.generated.mts must be generated from the Rust protocol contract",
    )
    fixture_source = (
        ROOT / "test" / "fixtures" / "protocol-v4-contract.json"
    ).read_text(encoding="utf-8")
    require(
        generated_marker not in fixture_source,
        "protocol fixture must remain independent from the Rust generator",
    )
    # Payload definition names are owned by the Rust generator. Keep this
    # architecture check focused on the stable generated entry points instead
    # of creating a second hand-maintained inventory here.
    for dto in (
        "clientToServerCustomNotification",
        "serverToClientCustomNotification",
        "methodResults",
    ):
        require(dto in protocol_schema["$defs"], f"protocol DTO {dto} is missing")

    serialized_schema = json.dumps(protocol_schema)
    for method in set(re.findall(r"fleximark/[A-Za-z]+", adapter_source)):
        require(method in serialized_schema, f"{method} is missing from protocol.schema.json")
    require("params?: unknown" not in adapter_source, "adapter uses an untyped params object")

    print(f"Verified {len(capabilities)} current capabilities.")


if __name__ == "__main__":
    script_entrypoint(verify_architecture)
