use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use fleximark_engine::{
    DocumentSession, PreviewSessionId, RenderAsset, RenderBlock, RenderFrame, RenderStyle,
};
use fleximark_model::{DocumentUri, PositionEncoding};
use fleximark_protocol::{
    AttachDocumentParams, AttachDocumentResult, CheckpointDocumentParams, CheckpointDocumentResult,
    ClientCapabilities, ClientInfo, CommandMessage, CommandResult, CreatePreviewParams,
    CreatePreviewResult, DisposePreviewParams, ExecuteCommandParams, GetNoteOptionsParams,
    GetNoteOptionsResult, InitializeParams, InitializeResult, MAX_SAFE_INTEGER, METHOD_SPECS,
    MethodDirection, MethodKind, MethodSpec, NavigationEntry, NodeId, NoteCategoryOption,
    PROTOCOL_VERSION, PreviewChangedParams, PreviewEventParams, PreviewNavigationEvent,
    PreviewTarget, ReadPreviewParams, ReadPreviewResult, ReconfigureWorkspaceParams,
    RenderNavigationEvent, RequestFullTextParams, RerenderPreviewParams, RpcChangeDocumentParams,
    RpcCloseDocumentParams, RpcId, RpcOpenDocumentParams, ServerCapabilities,
    ServerPreviewEventParams, SetSelectionParams, SetViewportParams, SourceNavigationEvent,
    SourcePosition, SourceRange, TextPosition, TextRange, TextSelection, WireType, WorkspaceGrant,
    WorkspaceStatus,
};
use fleximark_render_html::RenderContext;
use schemars::{JsonSchema, generate::SchemaSettings};
use serde_json::{Map, Value, json};

const GENERATED_COMMENT: &str = "Generated by fleximark-protocol-codegen; DO NOT EDIT.";
const SCHEMA_PATH: &str = "schemas/protocol.schema.json";
const TYPESCRIPT_PATH: &str = "web/preview-client/protocol.generated.mts";
const RUST_RENDER_FRAME_FIXTURE_PATH: &str = "test/fixtures/rust-render-frame-v4.json";

#[derive(Clone, Copy)]
enum Contract {
    Deserialize,
    Serialize,
}

struct NamedSchema {
    schema_name: &'static str,
    ts_name: &'static str,
    value: Value,
}

fn main() {
    if let Err(error) = run() {
        eprintln!("{error}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), String> {
    let mut arguments = env::args().skip(1);
    let command = arguments.next().ok_or_else(usage)?;
    if arguments.next().is_some() || !matches!(command.as_str(), "generate" | "check") {
        return Err(usage());
    }
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("codegen crate is directly under the workspace")
        .to_owned();
    let named = named_schemas();
    let outputs = [
        (root.join(SCHEMA_PATH), generate_protocol_schema(&named)?),
        (root.join(TYPESCRIPT_PATH), generate_typescript(&named)?),
        (
            root.join(RUST_RENDER_FRAME_FIXTURE_PATH),
            generate_render_frame_fixture()?,
        ),
    ];
    if command == "generate" {
        for (path, contents) in outputs {
            fs::write(&path, contents)
                .map_err(|error| format!("failed to write {}: {error}", path.display()))?;
            println!("generated {}", path.strip_prefix(&root).unwrap().display());
        }
    } else {
        let stale = outputs
            .into_iter()
            .filter_map(|(path, expected)| {
                (fs::read_to_string(&path).ok().as_deref() != Some(&expected)).then_some(path)
            })
            .collect::<Vec<_>>();
        if !stale.is_empty() {
            let paths = stale
                .iter()
                .map(|path| path.strip_prefix(&root).unwrap().display().to_string())
                .collect::<Vec<_>>()
                .join(", ");
            return Err(format!(
                "generated protocol contracts are stale: {paths}; run `cargo run -p fleximark-protocol-codegen -- generate`"
            ));
        }
        println!("generated protocol contracts are current");
    }
    Ok(())
}

fn generate_render_frame_fixture() -> Result<String, String> {
    let mut session = DocumentSession::open(
        DocumentUri("file:///rust-render-frame-fixture.md".to_owned()),
        7,
        "# Rust render frame\n\nGenerated by the engine.\n".to_owned(),
        PositionEncoding::Utf8,
    )
    .map_err(|error| format!("failed to open render-frame fixture: {error}"))?;
    let frame = session
        .render(
            PreviewSessionId("rust-render-frame-fixture".to_owned()),
            &RenderContext::default(),
        )
        .map_err(|error| format!("failed to render frame fixture: {error}"))?;
    serde_json::to_string_pretty(&frame)
        .map(|json| format!("{json}\n"))
        .map_err(|error| format!("failed to serialize render-frame fixture: {error}"))
}

fn usage() -> String {
    "usage: fleximark-protocol-codegen <generate|check>".to_owned()
}

fn derived_schema<T: JsonSchema>(contract: Contract) -> Value {
    let mut settings = SchemaSettings::draft2020_12();
    settings.inline_subschemas = false;
    settings = match contract {
        Contract::Deserialize => settings.for_deserialize(),
        Contract::Serialize => settings.for_serialize(),
    };
    let schema = settings.into_generator().into_root_schema_for::<T>();
    let mut value = serde_json::to_value(schema).expect("schemars schemas serialize");
    if let Value::Object(object) = &mut value {
        for key in ["$schema", "title", "description"] {
            object.remove(key);
        }
    }
    normalize_schema(&mut value, None);
    value
}

fn normalize_schema(value: &mut Value, property_name: Option<&str>) {
    match value {
        Value::Array(items) => items
            .iter_mut()
            .for_each(|item| normalize_schema(item, property_name)),
        Value::Object(object) => {
            if schema_declares_type(object, "integer") {
                if object
                    .get("minimum")
                    .and_then(Value::as_i64)
                    .is_none_or(|minimum| minimum < -MAX_SAFE_INTEGER)
                {
                    object.insert("minimum".to_owned(), json!(-MAX_SAFE_INTEGER));
                }
                if object
                    .get("maximum")
                    .and_then(Value::as_i64)
                    .is_none_or(|maximum| maximum > MAX_SAFE_INTEGER)
                {
                    object.insert("maximum".to_owned(), json!(MAX_SAFE_INTEGER));
                }
            }
            if object.get("type") == Some(&Value::String("object".to_owned()))
                && object.contains_key("properties")
            {
                object
                    .entry("additionalProperties")
                    .or_insert(Value::Bool(false));
            }
            match property_name {
                Some("protocolVersion") => {
                    object.clear();
                    object.insert("const".to_owned(), json!(PROTOCOL_VERSION));
                }
                Some("nodeExists") => {
                    object.clear();
                    object.insert("const".to_owned(), Value::Bool(true));
                }
                Some("renderRevision") => {
                    object.insert("minimum".to_owned(), json!(1));
                    object.insert("maximum".to_owned(), json!(MAX_SAFE_INTEGER));
                }
                Some("byteLength") => {
                    object.insert("minimum".to_owned(), json!(0));
                    object.insert("maximum".to_owned(), json!(1_048_576));
                }
                Some("line" | "character" | "byteStart" | "byteEnd" | "depth") => {
                    object.insert("minimum".to_owned(), json!(0));
                    object.insert("maximum".to_owned(), json!(MAX_SAFE_INTEGER));
                }
                _ => {}
            }
            if let Some(Value::Object(properties)) = object.get_mut("properties") {
                for (name, schema) in properties {
                    normalize_schema(schema, Some(name));
                    if matches!(name.as_str(), "error" | "url" | "message" | "openUri") {
                        remove_null_variant(schema);
                    }
                }
            }
            if object
                .get("properties")
                .and_then(Value::as_object)
                .is_some_and(|properties| properties.contains_key("activePosition"))
            {
                if let Some(Value::Array(required)) = object.get_mut("required") {
                    required.retain(|field| field.as_str() != Some("activePosition"));
                }
            }
            if let Some(Value::Object(definitions)) = object.get_mut("$defs") {
                for schema in definitions.values_mut() {
                    normalize_schema(schema, None);
                }
            }
            for key in ["items", "additionalProperties", "not", "if", "then", "else"] {
                if let Some(child) = object.get_mut(key) {
                    normalize_schema(child, property_name);
                }
            }
            for key in ["oneOf", "anyOf", "allOf"] {
                if let Some(Value::Array(children)) = object.get_mut(key) {
                    children
                        .iter_mut()
                        .for_each(|child| normalize_schema(child, property_name));
                }
            }
        }
        _ => {}
    }
}

fn remove_null_variant(schema: &mut Value) {
    if schema.get("type").is_some_and(Value::is_array) {
        let remaining_types = schema["type"]
            .as_array()
            .expect("type was checked as an array")
            .iter()
            .filter(|kind| kind.as_str() != Some("null"))
            .cloned()
            .collect::<Vec<_>>();
        schema["type"] = if remaining_types.len() == 1 {
            remaining_types[0].clone()
        } else {
            Value::Array(remaining_types)
        };
        return;
    }
    for key in ["anyOf", "oneOf"] {
        if let Some(variants) = schema.get_mut(key).and_then(Value::as_array_mut) {
            variants.retain(|variant| variant.get("type").and_then(Value::as_str) != Some("null"));
            if variants.len() == 1 {
                *schema = variants[0].clone();
            }
            return;
        }
    }
}

macro_rules! collect_named_schemas {
    ($(($variant:ident, $wire_name:literal, $schema_name:literal, $ts_name:literal, $type:ty, $contract:ident)),+ $(,)?) => {
        vec![$(NamedSchema {
            schema_name: $schema_name,
            ts_name: $ts_name,
            value: derived_schema::<$type>(Contract::$contract),
        }),+]
    };
}

fn named_schemas() -> Vec<NamedSchema> {
    let mut schemas = fleximark_protocol::for_each_contract_type!(collect_named_schemas);
    for schema in &mut schemas {
        rewrite_root_references(&mut schema.value, schema.schema_name);
    }
    schemas
}

fn rewrite_root_references(schema: &mut Value, schema_name: &str) {
    visit_schema_mut(schema, &mut |object| {
        if object.get("$ref").and_then(Value::as_str) == Some("#") {
            object.insert(
                "$ref".to_owned(),
                Value::String(format!("#/$defs/{schema_name}")),
            );
        }
    });
}

fn schema_ref(wire_type: WireType) -> Value {
    if wire_type == WireType::Unit {
        json!({ "type": "null" })
    } else {
        json!({ "$ref": format!("#/$defs/{}", wire_type.schema_name()) })
    }
}

fn local_ref(reference: &str) -> Result<&str, String> {
    reference
        .strip_prefix("#/$defs/")
        .ok_or_else(|| format!("unsupported schema reference: {reference}"))
}

fn method_variant(base: &str, method: &str, params: Value) -> Value {
    json!({ "allOf": [
        { "$ref": format!("#/$defs/{base}") },
        { "properties": { "method": { "const": method }, "params": params } }
    ] })
}

fn method_variants(
    base: &str,
    kind: MethodKind,
    params: impl Fn(&MethodSpec) -> Option<Value>,
) -> Vec<Value> {
    METHOD_SPECS
        .iter()
        .filter(|spec| spec.kind == kind)
        .filter_map(|spec| params(spec).map(|params| method_variant(base, spec.name, params)))
        .collect()
}

fn request_variants() -> Vec<Value> {
    method_variants("requestBase", MethodKind::Request, |spec| {
        Some(schema_ref(
            spec.client_to_server_params_type.expect("request params"),
        ))
    })
}

fn notification_variants(direction: MethodDirection) -> Vec<Value> {
    method_variants("notificationBase", MethodKind::Notification, |spec| {
        match direction {
            MethodDirection::ClientToServer => spec.client_to_server_params_type,
            MethodDirection::ServerToClient => spec.server_to_client_params_type,
            MethodDirection::Bidirectional => unreachable!(),
        }
        .map(schema_ref)
    })
}

fn combined_notification_variants() -> Vec<Value> {
    method_variants("notificationBase", MethodKind::Notification, |spec| {
        Some(
            match (
                spec.client_to_server_params_type,
                spec.server_to_client_params_type,
            ) {
                (Some(client), Some(server)) => {
                    json!({ "oneOf": [schema_ref(client), schema_ref(server)] })
                }
                (Some(params), None) | (None, Some(params)) => schema_ref(params),
                (None, None) => json!({ "type": "null" }),
            },
        )
    })
}

fn root_schema(value: &Value) -> Value {
    let mut root = value.clone();
    if let Some(object) = root.as_object_mut() {
        object.remove("$defs");
    }
    root
}

fn shared_definitions(named: &[NamedSchema]) -> Result<Map<String, Value>, String> {
    let mut shared = Map::new();
    for item in named {
        let Some(definitions) = item.value.get("$defs").and_then(Value::as_object) else {
            continue;
        };
        for (name, schema) in definitions {
            if let Some(previous) = shared.get(name) {
                if previous != schema {
                    return Err(format!("conflicting schemars definition: {name}"));
                }
            } else {
                shared.insert(name.clone(), schema.clone());
            }
        }
    }
    apply_semantic_overlays(&mut shared);
    flatten_tagged_variants(&mut shared)?;
    Ok(shared)
}

fn apply_semantic_overlays(definitions: &mut Map<String, Value>) {
    for (schema, property, keyword, value) in [
        (
            "RenderStyle",
            "fingerprint",
            "pattern",
            json!("^[0-9a-f]{64}$"),
        ),
        ("NavigationEntry", "nodeId", "minLength", json!(1)),
    ] {
        if let Some(schema) = definitions.get_mut(schema) {
            schema["properties"][property][keyword] = value;
        }
    }
    if let Some(asset) = definitions.get_mut("RenderAsset") {
        asset["properties"]["reference"]["pattern"] = json!("^fleximark-asset:[0-9a-f]{64}$");
        asset["properties"]["mediaType"] = json!({ "enum": [
            "image/png", "image/jpeg", "image/gif", "image/webp",
            "audio/mpeg", "audio/ogg", "audio/wav"
        ] });
        asset["properties"]["contentHash"]["pattern"] = json!("^[0-9a-f]{64}$");
        asset["properties"]["data"]["contentEncoding"] = json!("base64");
    }
    if let Some(block) = definitions.get_mut("RenderBlock") {
        block["properties"]["nodeIds"]["minItems"] = json!(1);
        block["properties"]["nodeIds"]["uniqueItems"] = json!(true);
        block["properties"]["nodeIds"]["items"]["minLength"] = json!(1);
    }
    for name in ["PreviewNavigationEvent", "RenderNavigationEvent"] {
        if let Some(schema) = definitions.get_mut(name) {
            add_nonempty_node_ids(schema);
        }
    }
    if let Some(options) = definitions.get_mut("GetNoteOptionsResult") {
        options["properties"]["categories"]["uniqueItems"] = json!(true);
        options["properties"]["templates"]["uniqueItems"] = json!(true);
    }
    if let Some(category) = definitions.get_mut("NoteCategoryOption") {
        category["properties"]["name"]["minLength"] = json!(1);
    }
    if let Some(params) = definitions.get_mut("ExecuteCommandParams") {
        let path = &mut params["properties"]["noteCategoryPath"];
        remove_null_variant(path);
        path["minItems"] = json!(1);
        path["maxItems"] = json!(32);
        path["items"]["minLength"] = json!(1);
    }
}

fn visit_schema_mut(schema: &mut Value, visitor: &mut impl FnMut(&mut Map<String, Value>)) {
    match schema {
        Value::Array(items) => items
            .iter_mut()
            .for_each(|item| visit_schema_mut(item, visitor)),
        Value::Object(object) => {
            visitor(object);
            object
                .values_mut()
                .for_each(|value| visit_schema_mut(value, visitor));
        }
        _ => {}
    }
}

fn add_nonempty_node_ids(schema: &mut Value) {
    visit_schema_mut(schema, &mut |object| {
        if let Some(Value::Object(properties)) = object.get_mut("properties") {
            for (name, value) in properties {
                if matches!(
                    name.as_str(),
                    "nodeId" | "parentId" | "currentParentId" | "previewSessionId"
                ) {
                    value["minLength"] = json!(1);
                } else if matches!(name.as_str(), "nodeIds" | "contentNodeIds") {
                    value["items"]["minLength"] = json!(1);
                    value["uniqueItems"] = json!(true);
                }
            }
        }
    });
}

fn schema_declares_type(object: &Map<String, Value>, expected: &str) -> bool {
    match object.get("type") {
        Some(Value::String(kind)) => kind == expected,
        Some(Value::Array(kinds)) => kinds.iter().any(|kind| kind.as_str() == Some(expected)),
        _ => false,
    }
}

fn flatten_tagged_variants(definitions: &mut Map<String, Value>) -> Result<(), String> {
    let snapshot = definitions.clone();
    for schema in definitions.values_mut() {
        flatten_tagged_schema(schema, &snapshot)?;
    }
    Ok(())
}

fn flatten_tagged_schema(
    schema: &mut Value,
    definitions: &Map<String, Value>,
) -> Result<(), String> {
    match schema {
        Value::Array(items) => {
            for item in items {
                flatten_tagged_schema(item, definitions)?;
            }
        }
        Value::Object(object) => {
            let tagged_reference = object
                .get("$ref")
                .and_then(Value::as_str)
                .zip(object.get("properties").and_then(Value::as_object))
                .filter(|(_, properties)| properties.contains_key("type"))
                .map(|(reference, _)| reference.to_owned());
            if let Some(reference) = tagged_reference {
                let name = local_ref(&reference)?;
                let mut merged = definitions
                    .get(name)
                    .cloned()
                    .ok_or_else(|| format!("missing tagged schema definition: {name}"))?;
                let merged_object = merged
                    .as_object_mut()
                    .ok_or_else(|| format!("tag target is not an object: {name}"))?;
                let tagged_properties = object.get("properties").cloned().unwrap();
                merged_object
                    .get_mut("properties")
                    .and_then(Value::as_object_mut)
                    .expect("tag target has properties")
                    .extend(tagged_properties.as_object().unwrap().clone());
                let mut required = merged_object
                    .remove("required")
                    .and_then(|value| value.as_array().cloned())
                    .unwrap_or_default();
                for field in object
                    .get("required")
                    .and_then(Value::as_array)
                    .into_iter()
                    .flatten()
                {
                    if !required.contains(field) {
                        required.push(field.clone());
                    }
                }
                merged_object.insert("required".to_owned(), Value::Array(required));
                *schema = merged;
            } else {
                for child in object.values_mut() {
                    flatten_tagged_schema(child, definitions)?;
                }
            }
        }
        _ => {}
    }
    Ok(())
}

fn contract_root(item: &NamedSchema, definitions: &Map<String, Value>) -> Result<Value, String> {
    let mut root = root_schema(&item.value);
    let mut singleton = Map::new();
    singleton.insert(item.ts_name.to_owned(), root);
    apply_semantic_overlays(&mut singleton);
    root = singleton
        .remove(item.ts_name)
        .expect("semantic overlay preserves its root");
    flatten_tagged_schema(&mut root, definitions)?;
    Ok(root)
}

fn generate_protocol_schema(named: &[NamedSchema]) -> Result<String, String> {
    let mut definitions = shared_definitions(named)?;
    definitions.insert("jsonValue".to_owned(), json!({
        "oneOf": [
            { "type": "null" }, { "type": "boolean" }, { "type": "number" }, { "type": "string" },
            { "type": "array", "items": { "$ref": "#/$defs/jsonValue" } },
            { "type": "object", "additionalProperties": { "$ref": "#/$defs/jsonValue" } }
        ]
    }));
    definitions.insert(
        "structuredParams".to_owned(),
        json!({ "oneOf": [
        { "type": "object", "additionalProperties": { "$ref": "#/$defs/jsonValue" } },
        { "type": "array", "items": { "$ref": "#/$defs/jsonValue" } }
    ] }),
    );
    definitions.insert("unit".to_owned(), json!({ "type": "null" }));
    for item in named {
        let root = contract_root(item, &definitions)?;
        if definitions
            .insert(item.schema_name.to_owned(), root)
            .is_some()
        {
            return Err(format!("duplicate schema name: {}", item.schema_name));
        }
    }
    definitions.insert(
        "responseId".to_owned(),
        json!({ "oneOf": [{ "$ref": "#/$defs/id" }, { "type": "null" }] }),
    );
    definitions.insert(
        "clientPreviewEventParams".to_owned(),
        json!({ "$ref": "#/$defs/previewEventParams" }),
    );
    definitions.insert("requestBase".to_owned(), json!({
        "type": "object", "additionalProperties": false,
        "properties": { "jsonrpc": { "const": "2.0" }, "id": { "$ref": "#/$defs/id" }, "method": { "type": "string" }, "params": { "type": "object" } },
        "required": ["jsonrpc", "id", "method", "params"]
    }));
    definitions.insert("notificationBase".to_owned(), json!({
        "type": "object", "additionalProperties": false,
        "properties": { "jsonrpc": { "const": "2.0" }, "method": { "type": "string" }, "params": { "type": "object" } },
        "required": ["jsonrpc", "method", "params"]
    }));
    definitions.insert(
        "customRequest".to_owned(),
        json!({ "oneOf": request_variants() }),
    );
    definitions.insert(
        "clientToServerCustomNotification".to_owned(),
        json!({ "oneOf": notification_variants(MethodDirection::ClientToServer) }),
    );
    definitions.insert(
        "serverToClientCustomNotification".to_owned(),
        json!({ "oneOf": notification_variants(MethodDirection::ServerToClient) }),
    );
    definitions.insert(
        "customNotification".to_owned(),
        json!({ "oneOf": combined_notification_variants() }),
    );
    definitions.insert("diagnostic".to_owned(), diagnostic_schema());
    definitions.insert("publishDiagnosticsParams".to_owned(), json!({
        "type": "object", "additionalProperties": false,
        "properties": { "uri": { "type": "string" }, "version": { "type": "integer" }, "diagnostics": { "type": "array", "items": { "$ref": "#/$defs/diagnostic" } } },
        "required": ["uri", "diagnostics"]
    }));
    definitions.insert("lspMessage".to_owned(), lsp_message_schema());
    definitions.insert("response".to_owned(), response_schema());
    let mut result_properties = Map::new();
    for spec in METHOD_SPECS {
        if spec.name != fleximark_protocol::method::REQUEST_FULL_TEXT {
            result_properties.insert(
                spec.name.to_owned(),
                spec.result_type
                    .map_or_else(|| json!({ "type": "null" }), schema_ref),
            );
        }
    }
    definitions.insert(
        "methodResults".to_owned(),
        json!({
            "type": "object", "description": "Named result DTOs for every FlexiMark method.",
            "properties": result_properties, "additionalProperties": false
        }),
    );

    let mut document = json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://fleximark.dev/schemas/protocol-v4.json",
        "$comment": GENERATED_COMMENT,
        "title": "FlexiMark JSON-RPC protocol v4",
        "oneOf": [
            { "$ref": "#/$defs/customRequest" }, { "$ref": "#/$defs/customNotification" },
            { "$ref": "#/$defs/lspMessage" }, { "$ref": "#/$defs/response" }
        ],
        "$defs": definitions
    });
    normalize_schema(&mut document, None);
    serde_json::to_string(&document)
        .map(|mut text| {
            text.push('\n');
            text
        })
        .map_err(|error| error.to_string())
}

fn diagnostic_schema() -> Value {
    json!({
        "type": "object", "additionalProperties": false,
        "properties": {
            "range": { "$ref": "#/$defs/range" }, "severity": { "type": "integer" }, "code": { "type": ["integer", "string"] },
            "codeDescription": { "type": "object", "additionalProperties": false, "properties": { "href": { "type": "string" } }, "required": ["href"] },
            "source": { "type": "string" }, "message": { "type": "string" }, "tags": { "type": "array", "items": { "type": "integer" } },
            "relatedInformation": { "type": "array", "items": { "type": "object", "additionalProperties": false,
                "properties": { "location": { "type": "object", "additionalProperties": false,
                    "properties": { "uri": { "type": "string" }, "range": { "$ref": "#/$defs/range" } }, "required": ["uri", "range"] },
                    "message": { "type": "string" } }, "required": ["location", "message"] } },
            "data": { "$ref": "#/$defs/jsonValue" }
        }, "required": ["range", "message"]
    })
}

fn lsp_message_schema() -> Value {
    json!({
        "type": "object", "additionalProperties": false,
        "properties": {
            "jsonrpc": { "const": "2.0" }, "id": { "$ref": "#/$defs/id" },
            "method": { "enum": ["initialize", "initialized", "shutdown", "exit", "textDocument/didOpen", "textDocument/didChange", "textDocument/didClose", "textDocument/completion", "textDocument/hover", "textDocument/documentSymbol", "textDocument/codeAction", "textDocument/diagnostic", "textDocument/publishDiagnostics"] },
            "params": { "$ref": "#/$defs/structuredParams" }
        }, "required": ["jsonrpc", "method"],
        "allOf": [{ "if": { "properties": { "method": { "const": "textDocument/publishDiagnostics" } }, "required": ["method"] },
            "then": { "properties": { "params": { "$ref": "#/$defs/publishDiagnosticsParams" } }, "required": ["params"] } }]
    })
}

fn response_schema() -> Value {
    json!({
        "type": "object", "additionalProperties": false,
        "properties": {
            "jsonrpc": { "const": "2.0" }, "id": { "$ref": "#/$defs/responseId" }, "result": { "$ref": "#/$defs/jsonValue" },
            "error": { "type": "object", "additionalProperties": false,
                "properties": { "code": { "type": "integer" }, "message": { "type": "string" }, "data": { "$ref": "#/$defs/jsonValue" } },
                "required": ["code", "message"] }
        }, "required": ["jsonrpc", "id"], "oneOf": [{ "required": ["result"] }, { "required": ["error"] }]
    })
}

fn generate_typescript(named: &[NamedSchema]) -> Result<String, String> {
    let mut output = format!("// {GENERATED_COMMENT}\n\n");
    output.push_str(&format!(
        "export const PROTOCOL_VERSION = {PROTOCOL_VERSION} as const;\n\n"
    ));
    let shared = shared_definitions(named)?;
    let mut exported = BTreeMap::new();
    for item in named {
        exported.insert(item.ts_name, item.ts_name);
        exported.insert(item.schema_name, item.ts_name);
    }
    for item in named {
        let root = contract_root(item, &shared)?;
        let schema = expand_type_refs(&root, &shared, &exported, false, &mut BTreeSet::new())?;
        output.push_str(&format!(
            "export type {} = {};\n\n",
            item.ts_name,
            schema_to_typescript(&schema)?
        ));
    }
    write_typescript_map(&mut output, "CustomRequestMap", |spec| {
        (spec.kind == MethodKind::Request).then(|| {
            let params = spec
                .client_to_server_params_type
                .expect("request params")
                .typescript_name();
            let result = spec.result_type.unwrap_or(WireType::Unit).typescript_name();
            format!("{{ params: {params}; result: {result} }}")
        })
    });
    write_typescript_map(&mut output, "ClientNotificationMap", |spec| {
        (spec.kind == MethodKind::Notification)
            .then_some(spec.client_to_server_params_type)
            .flatten()
            .map(|params| params.typescript_name().to_owned())
    });
    write_typescript_map(&mut output, "FleximarkServerNotificationMap", |spec| {
        (spec.kind == MethodKind::Notification)
            .then_some(spec.server_to_client_params_type)
            .flatten()
            .map(|params| params.typescript_name().to_owned())
    });

    let mut contract_definitions = shared;
    contract_definitions.insert("unit".to_owned(), json!({ "type": "null" }));
    let mut validator_roots = Map::new();
    validator_roots.insert("unit".to_owned(), json!({ "type": "null" }));
    for item in named {
        let root = contract_root(item, &contract_definitions)?;
        contract_definitions.insert(item.schema_name.to_owned(), root.clone());
        validator_roots.insert(item.schema_name.to_owned(), root);
    }
    let mut compiler = DescriptorCompiler::new(&contract_definitions);
    let type_validators = validator_roots
        .iter()
        .map(|(name, schema)| {
            compiler
                .compile_named(name, schema)
                .map(|index| (name.clone(), json!(index)))
        })
        .collect::<Result<Map<_, _>, _>>()?;
    write_json_const(&mut output, "VALIDATOR_TYPES", &compiler.pool)?;
    write_json_const(&mut output, "TYPE_VALIDATORS", &type_validators)?;
    let (requests, client_notifications, server_notifications) =
        method_validator_descriptors(&type_validators)?;
    for (name, value) in &[
        ("REQUEST_VALIDATORS", requests),
        ("CLIENT_NOTIFICATION_VALIDATORS", client_notifications),
        ("SERVER_NOTIFICATION_VALIDATORS", server_notifications),
    ] {
        write_json_const(&mut output, name, value)?;
    }
    output.push_str("export const WIRE_SCHEMAS = {\n");
    let mut wire_types = WireType::ALL.to_vec();
    wire_types.sort_by_key(|wire_type| wire_type.wire_name());
    for wire_type in wire_types {
        output.push_str(&format!(
            "  {:?}: {:?},\n",
            wire_type.wire_name(),
            wire_type.schema_name()
        ));
    }
    output.push_str("} as const;\n\nexport const METHOD_SPECS = [\n");
    for spec in METHOD_SPECS {
        output.push_str(&format!(
            "  {{ name: {:?}, direction: {:?}, kind: {:?}, clientToServerParamsType: {}, serverToClientParamsType: {}, resultType: {} }},\n",
            spec.name, direction_name(spec.direction), kind_name(spec.kind),
            option_wire_name(spec.client_to_server_params_type), option_wire_name(spec.server_to_client_params_type), option_wire_name(spec.result_type),
        ));
    }
    output.push_str("] as const;\n");
    Ok(output)
}

fn write_typescript_map(
    output: &mut String,
    name: &str,
    entry: impl Fn(&MethodSpec) -> Option<String>,
) {
    output.push_str(&format!("export interface {name} {{\n"));
    for spec in METHOD_SPECS {
        if let Some(value) = entry(spec) {
            output.push_str(&format!("  {:?}: {value};\n", spec.name));
        }
    }
    output.push_str("}\n\n");
}

fn write_json_const<T: serde::Serialize>(
    output: &mut String,
    name: &str,
    value: &T,
) -> Result<(), String> {
    output.push_str(&format!("export const {name} = "));
    output.push_str(&serde_json::to_string(value).map_err(|error| error.to_string())?);
    output.push_str(" as const;\n\n");
    Ok(())
}

type MethodValidatorDescriptors = (Map<String, Value>, Map<String, Value>, Map<String, Value>);

fn method_validator_descriptors(
    type_validators: &Map<String, Value>,
) -> Result<MethodValidatorDescriptors, String> {
    let index = |wire_type: WireType| -> Result<usize, String> {
        type_validators
            .get(wire_type.schema_name())
            .and_then(Value::as_u64)
            .map(|value| value as usize)
            .ok_or_else(|| format!("missing validator root: {}", wire_type.schema_name()))
    };
    let mut requests = Map::new();
    let mut client_notifications = Map::new();
    let mut server_notifications = Map::new();
    for spec in METHOD_SPECS {
        if spec.kind == MethodKind::Request {
            let params = spec.client_to_server_params_type.expect("request params");
            let result = spec.result_type.unwrap_or(WireType::Unit);
            requests.insert(
                spec.name.to_owned(),
                json!([index(params)?, index(result)?]),
            );
        } else {
            if let Some(params) = spec.client_to_server_params_type {
                client_notifications.insert(spec.name.to_owned(), json!(index(params)?));
            }
            if let Some(params) = spec.server_to_client_params_type {
                server_notifications.insert(spec.name.to_owned(), json!(index(params)?));
            }
        }
    }
    Ok((requests, client_notifications, server_notifications))
}

struct DescriptorCompiler<'a> {
    definitions: &'a Map<String, Value>,
    pool: Vec<Value>,
    interned: BTreeMap<String, usize>,
    named: BTreeMap<String, usize>,
}

impl<'a> DescriptorCompiler<'a> {
    fn new(definitions: &'a Map<String, Value>) -> Self {
        Self {
            definitions,
            pool: Vec::new(),
            interned: BTreeMap::new(),
            named: BTreeMap::new(),
        }
    }

    fn compile_named(&mut self, name: &str, schema: &Value) -> Result<usize, String> {
        if let Some(index) = self.named.get(name) {
            return Ok(*index);
        }
        let index = self.pool.len();
        self.pool.push(Value::Null);
        self.named.insert(name.to_owned(), index);
        let descriptor = self.descriptor(schema)?;
        self.pool[index] = descriptor.clone();
        self.interned
            .entry(serde_json::to_string(&descriptor).expect("descriptors serialize"))
            .or_insert(index);
        Ok(index)
    }

    fn compile(&mut self, schema: &Value) -> Result<usize, String> {
        if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
            let name = local_ref(reference)
                .map_err(|_| format!("unsupported validator reference: {reference}"))?;
            if let Some(index) = self.named.get(name) {
                return Ok(*index);
            }
            let target = self
                .definitions
                .get(name)
                .ok_or_else(|| format!("missing validator definition: {name}"))?
                .clone();
            return self.compile_named(name, &target);
        }
        let descriptor = self.descriptor(schema)?;
        Ok(self.intern(descriptor))
    }

    fn descriptor(&mut self, schema: &Value) -> Result<Value, String> {
        let object = schema
            .as_object()
            .ok_or_else(|| "boolean validator schemas are unsupported".to_owned())?;
        if let Some(value) = object.get("const") {
            return Ok(json!(["c", value]));
        }
        if let Some(Value::Array(values)) = object.get("enum") {
            let mut descriptor = vec![json!("e")];
            descriptor.extend(values.iter().cloned());
            return Ok(Value::Array(descriptor));
        }
        for key in ["oneOf", "anyOf", "allOf"] {
            if let Some(Value::Array(variants)) = object.get(key) {
                let opcode = if key == "allOf" { "l" } else { "u" };
                let mut descriptor = vec![json!(opcode)];
                for variant in variants {
                    descriptor.push(json!(self.compile(variant)?));
                }
                return Ok(Value::Array(descriptor));
            }
        }
        if let Some(Value::Array(types)) = object.get("type") {
            let mut descriptor = vec![json!("u")];
            for kind in types.iter().filter_map(Value::as_str) {
                let mut variant = object.clone();
                variant.insert("type".to_owned(), json!(kind));
                descriptor.push(json!(self.compile(&Value::Object(variant))?));
            }
            return Ok(Value::Array(descriptor));
        }
        match object.get("type").and_then(Value::as_str) {
            Some("null") => Ok(json!("z")),
            Some("boolean") => Ok(json!("b")),
            Some("integer") => Ok(constrained_descriptor("i", object, ["minimum", "maximum"])),
            Some("number") => Ok(constrained_descriptor("n", object, ["minimum", "maximum"])),
            Some("string") => Ok(constrained_descriptor(
                "s",
                object,
                ["pattern", "minLength", "maxLength"],
            )),
            Some("array") => {
                let item = object
                    .get("items")
                    .map(|schema| self.compile(schema))
                    .transpose()?
                    .unwrap_or_else(|| self.intern(json!("v")));
                Ok(with_optional_tail(
                    vec![json!("a"), json!(item)],
                    [
                        object.get("minItems").cloned(),
                        object.get("maxItems").cloned(),
                        object.get("uniqueItems").cloned(),
                    ],
                ))
            }
            Some("object") | None
                if object.contains_key("properties")
                    || object.contains_key("additionalProperties") =>
            {
                self.object_descriptor(object)
            }
            Some(_) | None => Ok(json!("v")),
        }
    }

    fn object_descriptor(&mut self, object: &Map<String, Value>) -> Result<Value, String> {
        let required = required_properties(object);
        let mut required_fields = Map::new();
        let mut optional_fields = Map::new();
        if let Some(properties) = object.get("properties").and_then(Value::as_object) {
            for (name, schema) in properties {
                let target = if required.contains(name.as_str()) {
                    &mut required_fields
                } else {
                    &mut optional_fields
                };
                target.insert(name.clone(), json!(self.compile(schema)?));
            }
        }
        let additional = match object.get("additionalProperties") {
            None | Some(Value::Bool(false)) => None,
            Some(Value::Bool(true)) => Some(self.intern(json!("v"))),
            Some(schema) => Some(self.compile(schema)?),
        };
        let property_names = object
            .get("propertyNames")
            .map(|schema| self.compile(schema))
            .transpose()?;
        Ok(with_optional_tail(
            vec![
                json!("o"),
                Value::Object(required_fields),
                Value::Object(optional_fields),
            ],
            [
                additional.map(|value| json!(value)),
                property_names.map(|value| json!(value)),
            ],
        ))
    }

    fn intern(&mut self, descriptor: Value) -> usize {
        let key = serde_json::to_string(&descriptor).expect("descriptors serialize");
        if let Some(index) = self.interned.get(&key) {
            return *index;
        }
        let index = self.pool.len();
        self.pool.push(descriptor);
        self.interned.insert(key, index);
        index
    }
}

fn with_optional_tail<const N: usize>(
    mut values: Vec<Value>,
    optional: [Option<Value>; N],
) -> Value {
    let mut tail = optional.map(|value| value.unwrap_or(Value::Null)).to_vec();
    while tail.last() == Some(&Value::Null) {
        tail.pop();
    }
    values.extend(tail);
    Value::Array(values)
}

fn constrained_descriptor<const N: usize>(
    opcode: &str,
    schema: &Map<String, Value>,
    constraints: [&str; N],
) -> Value {
    with_optional_tail(
        vec![json!(opcode)],
        constraints.map(|key| schema.get(key).cloned()),
    )
}

fn expand_type_refs(
    schema: &Value,
    definitions: &Map<String, Value>,
    exported: &BTreeMap<&str, &str>,
    preserve_exported: bool,
    stack: &mut BTreeSet<String>,
) -> Result<Value, String> {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        let name = local_ref(reference)?;
        if preserve_exported {
            if let Some(ts_name) = exported.get(name) {
                return Ok(json!({ "x-typescript-ref": ts_name }));
            }
        }
        if !stack.insert(name.to_owned()) {
            return Ok(json!({ "x-typescript-ref": name }));
        }
        let target = definitions
            .get(name)
            .ok_or_else(|| format!("missing schema definition: {name}"))?;
        let expanded = expand_type_refs(target, definitions, exported, true, stack)?;
        stack.remove(name);
        return Ok(expanded);
    }
    let mut expanded = schema.clone();
    match &mut expanded {
        Value::Array(items) => {
            for item in items {
                *item = expand_type_refs(item, definitions, exported, true, stack)?;
            }
        }
        Value::Object(object) => {
            object.remove("$defs");
            for value in object.values_mut() {
                *value = expand_type_refs(value, definitions, exported, true, stack)?;
            }
        }
        _ => {}
    }
    Ok(expanded)
}

fn option_wire_name(value: Option<WireType>) -> String {
    value.map_or_else(
        || "null".to_owned(),
        |wire_type| format!("{:?}", wire_type.wire_name()),
    )
}

fn direction_name(direction: MethodDirection) -> &'static str {
    match direction {
        MethodDirection::ClientToServer => "clientToServer",
        MethodDirection::ServerToClient => "serverToClient",
        MethodDirection::Bidirectional => "bidirectional",
    }
}

fn kind_name(kind: MethodKind) -> &'static str {
    match kind {
        MethodKind::Request => "request",
        MethodKind::Notification => "notification",
    }
}

fn schema_to_typescript(schema: &Value) -> Result<String, String> {
    let object = schema
        .as_object()
        .ok_or_else(|| "boolean schemas are unsupported in TypeScript output".to_owned())?;
    if let Some(reference) = object.get("x-typescript-ref").and_then(Value::as_str) {
        return Ok(reference.to_owned());
    }
    if let Some(value) = object.get("const") {
        return Ok(json_literal(value));
    }
    if let Some(Value::Array(values)) = object.get("enum") {
        return Ok(values
            .iter()
            .map(json_literal)
            .collect::<Vec<_>>()
            .join(" | "));
    }
    for (union_key, separator) in [("oneOf", " | "), ("anyOf", " | "), ("allOf", " & ")] {
        if let Some(Value::Array(items)) = object.get(union_key) {
            return items
                .iter()
                .map(schema_to_typescript)
                .collect::<Result<Vec<_>, _>>()
                .map(|items| items.join(separator));
        }
    }
    match object.get("type") {
        Some(Value::Array(types)) => types
            .iter()
            .map(|value| {
                let mut variant = object.clone();
                variant.insert("type".to_owned(), value.clone());
                schema_to_typescript(&Value::Object(variant))
            })
            .collect::<Result<Vec<_>, _>>()
            .map(|types| types.join(" | ")),
        Some(Value::String(kind)) if kind == "object" => object_schema_to_typescript(object),
        Some(Value::String(kind)) if kind == "array" => {
            let items = object
                .get("items")
                .map(schema_to_typescript)
                .transpose()?
                .unwrap_or_else(|| "unknown".to_owned());
            Ok(format!("Array<{items}>"))
        }
        Some(Value::String(kind)) => Ok(primitive_ts(kind).to_owned()),
        None if object.contains_key("properties") => object_schema_to_typescript(object),
        None => Ok("unknown".to_owned()),
        _ => Err("invalid schema type".to_owned()),
    }
}

fn object_schema_to_typescript(object: &Map<String, Value>) -> Result<String, String> {
    let required = required_properties(object);
    let mut fields = Vec::new();
    if let Some(properties) = object.get("properties").and_then(Value::as_object) {
        for (name, schema) in properties {
            fields.push(format!(
                "{}{}: {}",
                ts_property(name),
                if required.contains(name.as_str()) {
                    ""
                } else {
                    "?"
                },
                schema_to_typescript(schema)?
            ));
        }
    }
    if let Some(additional) = object.get("additionalProperties") {
        if additional != &Value::Bool(false) {
            let value_type = if additional == &Value::Bool(true) {
                "unknown".to_owned()
            } else {
                schema_to_typescript(additional)?
            };
            fields.push(format!("[key: string]: {value_type}"));
        }
    }
    Ok(format!("{{ {} }}", fields.join("; ")))
}

fn required_properties(object: &Map<String, Value>) -> BTreeSet<&str> {
    object
        .get("required")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .collect()
}

fn primitive_ts(kind: &str) -> &'static str {
    match kind {
        "null" => "null",
        "boolean" => "boolean",
        "integer" | "number" => "number",
        "string" => "string",
        "object" => "Record<string, unknown>",
        "array" => "unknown[]",
        _ => "unknown",
    }
}

fn json_literal(value: &Value) -> String {
    serde_json::to_string(value).expect("JSON literals serialize")
}

fn ts_property(name: &str) -> String {
    if name.chars().enumerate().all(|(index, character)| {
        character == '_'
            || character == '$'
            || (character.is_ascii_alphanumeric() && (index > 0 || !character.is_ascii_digit()))
    }) {
        name.to_owned()
    } else {
        json_literal(&Value::String(name.to_owned()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn schema_preserves_registry_frame_and_scalar_contracts() {
        let schema: Value =
            serde_json::from_str(&generate_protocol_schema(&named_schemas()).unwrap()).unwrap();
        assert_eq!(schema["$comment"], GENERATED_COMMENT);
        for definition in [
            "customRequest",
            "clientToServerCustomNotification",
            "serverToClientCustomNotification",
            "customNotification",
        ] {
            assert!(
                schema["$defs"][definition]["oneOf"].is_array(),
                "{definition}"
            );
        }
        let encoded = serde_json::to_string(&schema["$defs"]).unwrap();
        for spec in METHOD_SPECS {
            assert!(encoded.contains(spec.name), "{}", spec.name);
        }
        assert!(schema["$defs"]["renderFrame"]["properties"]["blocks"].is_object());
        assert_eq!(
            schema["$defs"]["createPreviewResult"]["required"],
            json!(["previewSessionId"])
        );
        assert_eq!(
            schema["$defs"]["readPreviewResult"]["properties"]["frame"]["anyOf"][0]["$ref"],
            "#/$defs/RenderFrame"
        );
        assert_safe_integer_bounds(&schema);

        assert_eq!(
            schema["$defs"]["renderBlock"]["properties"]["nodeIds"]["uniqueItems"],
            true
        );
        assert_eq!(
            schema["$defs"]["renderBlock"]["properties"]["nodeIds"]["minItems"],
            1
        );
        let category_path =
            &schema["$defs"]["executeCommandParams"]["properties"]["noteCategoryPath"];
        assert_eq!(category_path["type"], "array");
        assert_eq!(category_path["items"]["type"], "string");
        assert_eq!(category_path["items"]["minLength"], 1);
        assert_eq!(category_path["minItems"], 1);
        assert_eq!(category_path["maxItems"], 32);
    }

    fn assert_safe_integer_bounds(schema: &Value) {
        match schema {
            Value::Array(items) => items.iter().for_each(assert_safe_integer_bounds),
            Value::Object(object) => {
                if schema_declares_type(object, "integer") {
                    let minimum = object["minimum"].as_i64().expect("integer minimum");
                    let maximum = object["maximum"].as_i64().expect("integer maximum");
                    assert!(minimum >= -MAX_SAFE_INTEGER, "{object:?}");
                    assert!(maximum <= MAX_SAFE_INTEGER, "{object:?}");
                }
                object.values().for_each(assert_safe_integer_bounds);
            }
            _ => {}
        }
    }

    #[test]
    fn typescript_uses_compact_generated_validator_descriptors() {
        let output = generate_typescript(&named_schemas()).unwrap();
        assert!(output.starts_with("// Generated by fleximark-protocol-codegen; DO NOT EDIT."));
        assert!(output.contains("export const VALIDATOR_TYPES = "));
        assert!(output.contains("export const TYPE_VALIDATORS = "));
        assert!(output.contains("export const REQUEST_VALIDATORS = "));
        assert!(output.contains("export const CLIENT_NOTIFICATION_VALIDATORS = "));
        assert!(output.contains("export const SERVER_NOTIFICATION_VALIDATORS = "));
        assert!(!output.contains("export const CONTRACT_SCHEMA"));
        assert!(output.contains("frame: RenderFrame | null"));
        assert!(output.contains("level: \"info\" | \"warning\" | \"error\""));
        assert!(output.contains("noteCategoryPath?: Array<string>"));
    }
}
